// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parsyn.Apps.Company.Data.Contexts;

#nullable disable

namespace Parsyn.Apps.Company.Data.Migrations
{
    [DbContext(typeof(PDBContext))]
    [Migration("20250420184727_jdfhgdfgf")]
    partial class jdfhgdfgf
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Base.CustomerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsentLetter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MediaId")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Base.SeoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Keywords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Seo");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Bizbaan.Ad.AdCategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int?>("SeoId")
                        .HasColumnType("int");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("SeoId");

                    b.ToTable("AdCategories");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Bizbaan.Ad.AdImageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MediaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdId");

                    b.HasIndex("MediaId");

                    b.ToTable("AdImages");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Bizbaan.Ad.AdModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmbedMapAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSpecial")
                        .HasColumnType("bit");

                    b.Property<string>("Lat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lng")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SeoId")
                        .HasColumnType("int");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZipId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SeoId");

                    b.HasIndex("ZipId");

                    b.ToTable("Ads");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Bizbaan.Location.ZipModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("County_Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Distance")
                        .HasColumnType("float");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Some_Field")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State_Abbr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zipcode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zipcodes");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Config.MediaCatModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MediaCatModel");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Config.MediaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JsonFileSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaFileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrginalFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poster")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlInSitemap")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CatId");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Forms.FormModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Landing.ArticleCategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 6000L);

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("SeoId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SeoId");

                    b.ToTable("ArticleCategory");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Landing.ArticleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 5000L);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("SeoId")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SeoId");

                    b.ToTable("Article");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Landing.ContactUsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 7000L);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Phone1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SeoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeoId");

                    b.ToTable("ContactUs");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Landing.FaqCatModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("SeoId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SeoId");

                    b.ToTable("FaqCategory");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Landing.FaqModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("FaqCatId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Question")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FaqCatId");

                    b.ToTable("Faq");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Landing.PagesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SeoId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SeoId");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Landing.SocialMediaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SocialMedia");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.OptionsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Reactions.CommentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArticleModelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("IP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ArticleModelId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Reactions.LikeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArticleModelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("IP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ArticleModelId");

                    b.ToTable("Like");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Reactions.SubscribeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Subscribe");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Reactions.VisitModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArticleModelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("IP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ArticleModelId");

                    b.ToTable("Visit");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.User.PermissionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Code")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int?>("Sort")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.User.RoleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.User.RolePermissionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.User.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("FailAccessCount")
                        .HasColumnType("int");

                    b.Property<string>("Family")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("ForceChangePassword")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Otp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OtpValidTo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PrivateKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<bool>("WaitForOtp")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Base.CustomerModel", b =>
                {
                    b.HasOne("Parsyn.Apps.Company.Data.Models.Entity.Config.MediaModel", "Image")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Bizbaan.Ad.AdCategoryModel", b =>
                {
                    b.HasOne("Parsyn.Apps.Company.Data.Models.Entity.Bizbaan.Ad.AdCategoryModel", "Parent")
                        .WithMany("Childs")
                        .HasForeignKey("ParentId");

                    b.HasOne("Parsyn.Apps.Company.Data.Models.Entity.Base.SeoModel", "Seo")
                        .WithMany()
                        .HasForeignKey("SeoId");

                    b.Navigation("Parent");

                    b.Navigation("Seo");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Bizbaan.Ad.AdImageModel", b =>
                {
                    b.HasOne("Parsyn.Apps.Company.Data.Models.Entity.Bizbaan.Ad.AdModel", "Ad")
                        .WithMany("Images")
                        .HasForeignKey("AdId");

                    b.HasOne("Parsyn.Apps.Company.Data.Models.Entity.Config.MediaModel", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId");

                    b.Navigation("Ad");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Bizbaan.Ad.AdModel", b =>
                {
                    b.HasOne("Parsyn.Apps.Company.Data.Models.Entity.Bizbaan.Ad.AdCategoryModel", "Category")
                        .WithMany("Ads")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parsyn.Apps.Company.Data.Models.Entity.Base.SeoModel", "Seo")
                        .WithMany()
                        .HasForeignKey("SeoId");

                    b.HasOne("Parsyn.Apps.Company.Data.Models.Entity.Bizbaan.Location.ZipModel", "Zip")
                        .WithMany("Ads")
                        .HasForeignKey("ZipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Seo");

                    b.Navigation("Zip");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Config.MediaModel", b =>
                {
                    b.HasOne("Parsyn.Apps.Company.Data.Models.Entity.Config.MediaCatModel", "Category")
                        .WithMany("Medias")
                        .HasForeignKey("CatId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Landing.ArticleCategoryModel", b =>
                {
                    b.HasOne("Parsyn.Apps.Company.Data.Models.Entity.Base.SeoModel", "Seo")
                        .WithMany()
                        .HasForeignKey("SeoId");

                    b.Navigation("Seo");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Landing.ArticleModel", b =>
                {
                    b.HasOne("Parsyn.Apps.Company.Data.Models.Entity.Landing.ArticleCategoryModel", "ArticleCategory")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parsyn.Apps.Company.Data.Models.Entity.Base.SeoModel", "Seo")
                        .WithMany()
                        .HasForeignKey("SeoId");

                    b.Navigation("ArticleCategory");

                    b.Navigation("Seo");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Landing.ContactUsModel", b =>
                {
                    b.HasOne("Parsyn.Apps.Company.Data.Models.Entity.Base.SeoModel", "Seo")
                        .WithMany()
                        .HasForeignKey("SeoId");

                    b.Navigation("Seo");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Landing.FaqCatModel", b =>
                {
                    b.HasOne("Parsyn.Apps.Company.Data.Models.Entity.Base.SeoModel", "Seo")
                        .WithMany()
                        .HasForeignKey("SeoId");

                    b.Navigation("Seo");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Landing.FaqModel", b =>
                {
                    b.HasOne("Parsyn.Apps.Company.Data.Models.Entity.Landing.FaqCatModel", "FaqCat")
                        .WithMany("Faqs")
                        .HasForeignKey("FaqCatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FaqCat");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Landing.PagesModel", b =>
                {
                    b.HasOne("Parsyn.Apps.Company.Data.Models.Entity.Base.SeoModel", "Seo")
                        .WithMany()
                        .HasForeignKey("SeoId");

                    b.Navigation("Seo");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Reactions.CommentModel", b =>
                {
                    b.HasOne("Parsyn.Apps.Company.Data.Models.Entity.Landing.ArticleModel", null)
                        .WithMany("Comments")
                        .HasForeignKey("ArticleModelId");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Reactions.LikeModel", b =>
                {
                    b.HasOne("Parsyn.Apps.Company.Data.Models.Entity.Landing.ArticleModel", null)
                        .WithMany("Likes")
                        .HasForeignKey("ArticleModelId");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Reactions.VisitModel", b =>
                {
                    b.HasOne("Parsyn.Apps.Company.Data.Models.Entity.Landing.ArticleModel", null)
                        .WithMany("Visits")
                        .HasForeignKey("ArticleModelId");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.User.PermissionModel", b =>
                {
                    b.HasOne("Parsyn.Apps.Company.Data.Models.Entity.User.PermissionModel", "Parent")
                        .WithMany("Childs")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.User.RolePermissionModel", b =>
                {
                    b.HasOne("Parsyn.Apps.Company.Data.Models.Entity.User.PermissionModel", "Permission")
                        .WithMany("Roles")
                        .HasForeignKey("PermissionId");

                    b.HasOne("Parsyn.Apps.Company.Data.Models.Entity.User.RoleModel", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.User.UserModel", b =>
                {
                    b.HasOne("Parsyn.Apps.Company.Data.Models.Entity.User.RoleModel", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Bizbaan.Ad.AdCategoryModel", b =>
                {
                    b.Navigation("Ads");

                    b.Navigation("Childs");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Bizbaan.Ad.AdModel", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Bizbaan.Location.ZipModel", b =>
                {
                    b.Navigation("Ads");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Config.MediaCatModel", b =>
                {
                    b.Navigation("Medias");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Landing.ArticleCategoryModel", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Landing.ArticleModel", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.Landing.FaqCatModel", b =>
                {
                    b.Navigation("Faqs");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.User.PermissionModel", b =>
                {
                    b.Navigation("Childs");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Parsyn.Apps.Company.Data.Models.Entity.User.RoleModel", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
